[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "BfUDnWQ2en87Hy6s2wdRNN28vbRYHk7FsQ8DQc3TADsb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
